version: '3.8'

services:
  app_blue:
    build: .
    container_name: moviezip-app-blue
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      MONGODB_URI: mongodb://host.docker.internal:27017/movieZip
