version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: moviezip-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.4
    container_name: moviezip-mongo
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]

  app_blue:
    build: .
    container_name: moviezip-app-blue
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod