spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@dblab.dongduk.ac.kr:1521/orclpdb
    username: ss240205
    password: ss240205ss

  data:
    mongodb:
      uri: mongodb://localhost:27017/movieZip

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
