spring:
  application:
    name: moviezip
mybatis:
  type-aliases-package: com.example.moviezip.domain

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

token:
  access-token-expire-time: 3000000
  refresh-token-expire-time: 604800000